name: Benchmarking With Docker Compose

on:
  workflow_dispatch:

jobs:
  benchmark_solarwinds_apm:
    name: run benchmark
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false

    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    - name: Setup
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install apache2-utils
        docker compose -f ./.github/workflows/scripts/docker-compose.yml up -d
        sleep 5

    - name: Benchmark
      run: |
        ab -n 1000 -c 10 http://0.0.0.0:8002/ &
        P1=$!
        ab -n 1000 -c 10 http://0.0.0.0:8003/ &
        P2=$!
        wait $P1 $P2



# echo "Running without solarwinds_apm"
# ab -n 20 -c 2 http://0.0.0.0:8002/
# sleep 10
# echo "Running WITH solarwinds_apm"
# ab -n 20 -c 2 http://0.0.0.0:8003/
