name: Verify Installation Direct Approach ON AMD64

on:
  workflow_dispatch:
    inputs:
      install-registry:
        required: true
        description: 'Registry used for install tests, e.g. RubyGem, packagecloud'
        type: choice
        default: 'RubyGem'
        options:
        - RubyGem
        - packagecloud

      solarwinds-version:
        required: true
        description: 'Solarwinds apm version'

env:
  SOLARWINDS_APM_VERSION: ${{ github.event.inputs.solarwinds-version }}
  SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}
  SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
  PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

jobs:
  verify_install_amd64_test:
    name: ruby - ${{ matrix.ruby_version }} - amd64 - ${{ github.event.inputs.solarwinds-version }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        # os: [3.1.3-bullseye, 2.7.7-bullseye, 3.1.3-alpine3.17, 2.7.7-alpine3.16]
        ruby_version: ['3.1.0']

    steps:
      - uses: actions/checkout@v3
      - run: docker pull redhat/ubi8
      - name: Run tests in container
        run: |
          sudo docker run \
            --platform linux/amd64 \
            -e RUBY_VERSION=${{ matrix.ruby_version }} \
            -e SW_APM_SERVICE_KEY=${{ secrets.SW_APM_SERVICE_KEY }} \
            -e SW_APM_COLLECTOR=${{ secrets.SW_APM_COLLECTOR }} \
            -e SOLARWINDS_APM_VERSION=${{ github.event.inputs.solarwinds-version }} \
            -e PACKAGECLOUD_TOKEN=${{ secrets.PACKAGECLOUD_TOKEN }} \
            -v $(pwd):/home \
            --rm redhat/ubi8 \
            ./home/extra_test.sh


# without cd home/
# the directory is the /root
# cd to other directory will lose the environmental variable