name: Verify Installation

on:
  workflow_dispatch:


jobs:
  #--------------------------------------------------------------------
  # RUBY 3.1
  #--------------------------------------------------------------------

  ruby31_install_ubuntu_20_arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        working-directory: .github/workflows/
        with:
          arch: aarch64
          distro: ubuntu22.04

          run: |
            sleep 1
            gem install solarwinds_apm
            ruby ./scripts/verify_install.rb
