name: Verify Installation

on:
  workflow_dispatch:
    inputs:
      install-registry:
        required: true
        description: 'Registry used for install tests, e.g. RubyGem, packagecloud'
        type: choice
        default: 'RubyGem'
        options:
        - RubyGem
        - packagecloud

      solarwinds-version:
        required: true
        description: 'Solarwinds apm version'

env:
  SOLARWINDS_APM_VERSION: ${{ github.event.inputs.solarwinds-version }}
  SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}
  SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
  PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

jobs:

  verify_install_amd64_test:
    name: ruby - ${{ matrix.os }} amd64 - ${{ github.event.inputs.solarwinds-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [3.1.3-bullseye, 2.7.7-bullseye, 3.1.3-alpine3.17, 2.7.7-alpine3.16]

    container:
      image: ruby:${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup and run install test
        working-directory: .github/workflows/
        run: ./scripts/_helper_run_install_tests.sh
        shell: sh
        env:
          MODE: ${{ github.event.inputs.install-registry }}
          ARCHITECTURE: AMD


  # this use base_image from uraimo/run-on-arch-action@v2
  # verify_install_arm64_test:
  #   name: ruby - ${{ matrix.os }} arm64 - ${{ github.event.inputs.solarwinds-version }}
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [3.1.3-bullseye, 2.7.7-bullseye, 3.1.3-alpine3.17, 2.7.7-alpine3.16]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: uraimo/run-on-arch-action@v2
  #       name: Verify Install
  #       with:
  #         arch: none
  #         distro: none
  #         base_image: arm64v8/ruby:${{ matrix.os }}
  #         run: |
  #           ./.github/workflows/scripts/_helper_run_install_tests.sh
  #         env: |
  #           MODE: ${{ github.event.inputs.install-registry }}
  #           ARCHITECTURE: ARM
  #           SOLARWINDS_APM_VERSION: ${{ github.event.inputs.solarwinds-version }}
  #           SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}
  #           SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
  #           PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}


  verify_install_arm64_test:
    name: ruby - ${{ matrix.os }} arm64 - ${{ github.event.inputs.solarwinds-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, ubuntu20.04, ubuntu18.04, alpine_latest]

    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Verify Install
        with:
          arch: aarch64
          distro: ${{ matrix.os }}
          run: |
            ./.github/workflows/scripts/_helper_run_install_tests.sh
          env: |
            MODE: ${{ github.event.inputs.install-registry }}
            ARCHITECTURE: ARM
            SOLARWINDS_APM_VERSION: ${{ github.event.inputs.solarwinds-version }}
            SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY }}
            SW_APM_COLLECTOR: ${{ secrets.SW_APM_COLLECTOR }}
            PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}






