name: "Release Ruby Lambda Layer"

on:
  # (Using tag push instead of release to allow filtering by tag prefix.)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-layer:
    runs-on: ubuntu-latest
    outputs:
      RUBY_SDK_VERSION: ${{ steps.save-ruby-sdk-version.outputs.RUBY_SDK_VERSION}}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install SAM
        run: |
          sudo apt-get update && sudo apt-get install wget unzip make -y
          wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
          ./sam-installation/install --update

      - name: Build
        id: save-ruby-sdk-version
        run: |
          sam build -u -t template.yml
          export GEM_PATH=$PWD/.aws-sam/build/OTelLayer/ruby/gems/3.2.0/
          RUBY_SDK_VERSION=$(ruby -e 'require "opentelemetry-sdk"; puts OpenTelemetry::SDK::VERSION')
          echo "RUBY_SDK_VERSION=$RUBY_SDK_VERSION" >> $GITHUB_OUTPUT
        working-directory: ruby/src

      - name: Zip the layer file
        run: |
          echo ${{ steps.save-ruby-sdk-version.outputs.RUBY_SDK_VERSION}}
          ./zip_ruby_layer.sh
        working-directory: ruby/src
        shell: bash

      - uses: actions/upload-artifact@v4
        name: Save assembled layer to build
        with:
          name: opentelemetry-ruby-layer.zip
          path: ruby/src/opentelemetry-ruby-layer.zip
