name: Verify Installation

on:
  workflow_dispatch:


jobs:
  #--------------------------------------------------------------------
  # RUBY 3.1
  #--------------------------------------------------------------------

  ruby31_install_ubuntu_20_arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04

          run: |
            sleep 1
            apt update
            apt install -y ruby ruby-dev libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
            gem install solarwinds_apm
            ruby ./.github/workflows/scripts/verify_install.rb
