name: "Test ARM Runner"

on:
  # (Using tag push instead of release to allow filtering by tag prefix.)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  test-arm-runner:
    runs-on: ubuntu-latest-arm64

    steps:
      - uses: actions/checkout@v4

      - name: reveal the architecture
        run: |
          uname -a
